version: '3.8'

services:
  nominatim:
    image: mediagis/nominatim:4.5
    container_name: nominatim
    ports:
      - "8080:8080"
    environment:
      - NOMINATIM_IMPORT=1      # Para importar os dados (lembre-se: a primeira importação pode levar tempo)
      - PBF_URL=https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
    volumes:
      - nominatim_data:/var/lib/postgresql/16/main
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - nominatim
    restart: unless-stopped

volumes:
  nominatim_data:
